package com.saywa.framework.data.kms.domain;

/**
 * Data key generated by KMS for envelope encryption: it travels in plain
 * text (to cipher locally with AES-GCM) and encrypted under the CMK (to
 * persist alongside the data). The plaintext form is never stored — only
 * used in memory for the duration of a single {@code wrap}/{@code unwrap}
 * call.
 *
 * @param keyId        identifier of the CMK that wrapped {@code encryptedKey}.
 * @param spec         length of {@code plaintextKey}.
 * @param plaintextKey the raw AES key material; {@code null} once wiped.
 * @param encryptedKey {@code plaintextKey} encrypted under the CMK; safe to
 *                     persist.
 */
public record DataKey(
        String keyId,
        DataKeySpec spec,
        byte[] plaintextKey,
        byte[] encryptedKey) {

    /**
     * @return a copy of this data key with the plaintext material removed,
     *         safe to expose or log when the caller must not see it.
     */
    public DataKey withoutPlaintext() {
        return new DataKey(keyId, spec, null, encryptedKey);
    }
}
